version: "3"
include:
  - proxy.yaml
services:

  db:
    image: mysql:8
    env_file:
      - .env
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-very_strong}
    restart: always
    networks:
      backend:
        ipv4_address: 172.20.0.10

  web:
    build:
      context: .
      dockerfile: Dockerfile.python
    env_file:
      - .env
    environment:
      - DB_HOST=172.20.0.10
      - DB_USER=${MYSQL_USER:-app}
      - DB_PASSWORD=${MYSQL_PASSWORD:-very_strong}
      - DB_NAME=${MYSQL_DATABASE:-example}
      - DB_TABLE_NAME=${MYSQL_TABLE_NAME:-example}
    restart: always
    networks:
      backend:
        ipv4_address: 172.20.0.5

